# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formularioMultip.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formularioMultip(object):
    def setupUi(self, formularioMultip):
        formularioMultip.setObjectName("formularioMultip")
        formularioMultip.resize(369, 308)
        self.label = QtWidgets.QLabel(formularioMultip)
        self.label.setGeometry(QtCore.QRect(110, 50, 141, 21))
        self.label.setObjectName("label")
        self.pbAceptar = QtWidgets.QPushButton(formularioMultip)
        self.pbAceptar.setGeometry(QtCore.QRect(80, 270, 75, 23))
        self.pbAceptar.setObjectName("pbAceptar")
        self.pbCerrar = QtWidgets.QPushButton(formularioMultip)
        self.pbCerrar.setGeometry(QtCore.QRect(200, 270, 75, 23))
        self.pbCerrar.setObjectName("pbCerrar")
        self.layoutWidget = QtWidgets.QWidget(formularioMultip)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 200, 201, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lblresultado = QtWidgets.QLabel(self.layoutWidget)
        self.lblresultado.setText("")
        self.lblresultado.setObjectName("lblresultado")
        self.horizontalLayout_5.addWidget(self.lblresultado)
        self.widget = QtWidgets.QWidget(formularioMultip)
        self.widget.setGeometry(QtCore.QRect(81, 100, 173, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtdato1 = QtWidgets.QLineEdit(self.widget)
        self.txtdato1.setObjectName("txtdato1")
        self.horizontalLayout.addWidget(self.txtdato1)
        self.widget1 = QtWidgets.QWidget(formularioMultip)
        self.widget1.setGeometry(QtCore.QRect(81, 150, 173, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txtdato2 = QtWidgets.QLineEdit(self.widget1)
        self.txtdato2.setObjectName("txtdato2")
        self.horizontalLayout_2.addWidget(self.txtdato2)

        self.retranslateUi(formularioMultip)
        QtCore.QMetaObject.connectSlotsByName(formularioMultip)

    def retranslateUi(self, formularioMultip):
        _translate = QtCore.QCoreApplication.translate
        formularioMultip.setWindowTitle(_translate("formularioMultip", "Dialog"))
        self.label.setText(_translate("formularioMultip", "<html><head/><body><p>FORMULARIO MULTIPLICAR</p></body></html>"))
        self.pbAceptar.setText(_translate("formularioMultip", "Aceptar"))
        self.pbCerrar.setText(_translate("formularioMultip", "Cerrar"))
        self.label_7.setText(_translate("formularioMultip", "Resultado"))
        self.label_2.setText(_translate("formularioMultip", "Dato 1"))
        self.label_5.setText(_translate("formularioMultip", "Dato 2"))
