# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuprogramas = QtWidgets.QMenu(self.menuBar)
        self.menuprogramas.setObjectName("menuprogramas")
        self.menuAcerca_de = QtWidgets.QMenu(self.menuBar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionmultiplicar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/numeros.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmultiplicar.setIcon(icon)
        self.actionmultiplicar.setObjectName("actionmultiplicar")
        self.actionNumero_primo = QtWidgets.QAction(MainWindow)
        self.actionNumero_primo.setObjectName("actionNumero_primo")
        self.actionNumero_Par = QtWidgets.QAction(MainWindow)
        self.actionNumero_Par.setObjectName("actionNumero_Par")
        self.actionNumero_perfecto = QtWidgets.QAction(MainWindow)
        self.actionNumero_perfecto.setObjectName("actionNumero_perfecto")
        self.actionNumero_Exponencial = QtWidgets.QAction(MainWindow)
        self.actionNumero_Exponencial.setObjectName("actionNumero_Exponencial")
        self.menuprogramas.addAction(self.actionmultiplicar)
        self.menuprogramas.addAction(self.actionNumero_primo)
        self.menuprogramas.addAction(self.actionNumero_Par)
        self.menuprogramas.addAction(self.actionNumero_perfecto)
        self.menuprogramas.addAction(self.actionNumero_Exponencial)
        self.menuBar.addAction(self.menuprogramas.menuAction())
        self.menuBar.addAction(self.menuAcerca_de.menuAction())
        self.toolBar.addAction(self.actionmultiplicar)
        self.toolBar.addAction(self.actionNumero_primo)
        self.toolBar.addAction(self.actionNumero_Par)
        self.toolBar.addAction(self.actionNumero_perfecto)
        self.toolBar.addAction(self.actionNumero_Exponencial)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuprogramas.setTitle(_translate("MainWindow", "Programas"))
        self.menuAcerca_de.setTitle(_translate("MainWindow", "Acerca de"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionmultiplicar.setText(_translate("MainWindow", "multiplicar"))
        self.actionNumero_primo.setText(_translate("MainWindow", "Numero primo"))
        self.actionNumero_Par.setText(_translate("MainWindow", "Numero Par"))
        self.actionNumero_perfecto.setText(_translate("MainWindow", "Numero perfecto"))
        self.actionNumero_Exponencial.setText(_translate("MainWindow", "Numero Exponencial"))
#import imagenes_rc
