# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numeroExponencial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_numeroExponencial(object):
    def setupUi(self, numeroExponencial):
        numeroExponencial.setObjectName("numeroExponencial")
        numeroExponencial.resize(400, 300)
        self.label = QtWidgets.QLabel(numeroExponencial)
        self.label.setGeometry(QtCore.QRect(130, 20, 131, 31))
        self.label.setObjectName("label")
        self.pb_aceptar = QtWidgets.QPushButton(numeroExponencial)
        self.pb_aceptar.setGeometry(QtCore.QRect(150, 180, 75, 23))
        self.pb_aceptar.setObjectName("pb_aceptar")
        self.result = QtWidgets.QLabel(numeroExponencial)
        self.result.setGeometry(QtCore.QRect(80, 220, 251, 41))
        self.result.setObjectName("result")
        self.widget = QtWidgets.QWidget(numeroExponencial)
        self.widget.setGeometry(QtCore.QRect(70, 100, 261, 61))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtnum = QtWidgets.QLineEdit(self.widget)
        self.txtnum.setObjectName("txtnum")
        self.gridLayout.addWidget(self.txtnum, 1, 0, 1, 1)

        self.retranslateUi(numeroExponencial)
        QtCore.QMetaObject.connectSlotsByName(numeroExponencial)

    def retranslateUi(self, numeroExponencial):
        _translate = QtCore.QCoreApplication.translate
        numeroExponencial.setWindowTitle(_translate("numeroExponencial", "Dialog"))
        self.label.setText(_translate("numeroExponencial", "NUMERO EXPONENCIAL"))
        self.pb_aceptar.setText(_translate("numeroExponencial", "Aceptar"))
        self.result.setText(_translate("numeroExponencial", "TextLabel"))
        self.label_2.setText(_translate("numeroExponencial", "INGRESE UN NUMERO"))
