# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numeroprimo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_numeroPrimo(object):
    def setupUi(self, numeroPrimo):
        numeroPrimo.setObjectName("numeroPrimo")
        numeroPrimo.resize(320, 240)
        self.label = QtWidgets.QLabel(numeroPrimo)
        self.label.setGeometry(QtCore.QRect(90, 20, 141, 41))
        self.label.setObjectName("label")
        self.resultPrimos = QtWidgets.QLabel(numeroPrimo)
        self.resultPrimos.setGeometry(QtCore.QRect(40, 180, 249, 34))
        self.resultPrimos.setText("")
        self.resultPrimos.setObjectName("resultPrimos")
        self.layoutWidget = QtWidgets.QWidget(numeroPrimo)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 70, 251, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtNumPrimo = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNumPrimo.setObjectName("txtNumPrimo")
        self.gridLayout.addWidget(self.txtNumPrimo, 2, 0, 1, 1)
        self.pbAceptarNumPrimo = QtWidgets.QPushButton(self.layoutWidget)
        self.pbAceptarNumPrimo.setObjectName("pbAceptarNumPrimo")
        self.gridLayout.addWidget(self.pbAceptarNumPrimo, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(numeroPrimo)
        QtCore.QMetaObject.connectSlotsByName(numeroPrimo)

    def retranslateUi(self, numeroPrimo):
        _translate = QtCore.QCoreApplication.translate
        numeroPrimo.setWindowTitle(_translate("numeroPrimo", "Dialog"))
        self.label.setText(_translate("numeroPrimo", "NUMERO PRIMOS"))
        self.pbAceptarNumPrimo.setText(_translate("numeroPrimo", "Aceptar"))
        self.label_2.setText(_translate("numeroPrimo", "Ingrese un numero para saber si es primo o no:"))
